use_frameworks!

platform :ios, '8.0'

target 'ZKPreviewController_Example' do
  pod 'ZKPreviewController', :path => '../'

  target 'ZKPreviewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
